---
- name: Disabled service getty@tty1
  systemd:
    name: getty@tty1
    state: disabled
    enabled: true

- name: Disabled service getty-static
  systemd:
    name: getty-static
    state: disabled
    enabled: true

- name: Copy logind.conf
  template:
    src: logind.conf.j2
    dest: "/etc/systemd/logind.conf"
  become: true
