---
- name: Stopped service getty@tty1
  systemd:
    name: getty@tty1
    state: stopped
    enabled: false

- name: Stopped service getty-static
  systemd:
    name: getty-static
    state: stopped
    enabled: false

- name: Copy logind.conf
  template:
    src: logind.conf.j2
    dest: "/etc/systemd/logind.conf"
  become: true
