---
- name: Install utils
  apt:
    pkg:
      - nyancat
    update_cache: yes
    cache_valid_time: 3600

- name: systemd service
  template:
    src: nyancat-tty.service.j2
    dest: /etc/systemd/system/nyancat-tty.service

- name: systemd reload
  systemd:
    daemon_reload: yes

- name: systemd service enable
  systemd:
    name: nyancat-tty.service
    enabled: yes
